controller_list:
  - name: "irb6640"
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - irb6640_joint_1
      - irb6640_joint_2
      - irb6640_joint_3
      - irb6640_joint_4
      - irb6640_joint_5
      - irb6640_joint_6
      - irb6640_track_1
  - name: "irb4400"
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - irb4400_joint_1
      - irb4400_joint_2
      - irb4400_joint_3
      - irb4400_joint_4
      - irb4400_joint_5
      - irb4400_joint_6